export const RUTOR_CATEGORIES_QUERY_ANY = 'any';
export const RUTOR_CATEGORIES_QUERY_MOVIES = 'movies';
export const RUTOR_CATEGORIES_QUERY_SERIES = 'series';
export const RUTOR_CATEGORIES_QUERY_TVSHOWS = 'tvshows';
export const RUTOR_CATEGORIES_QUERY_CARTOONS = 'cartoons';
export const RUTOR_CATEGORIES_QUERY_ANIME = 'anime';

export const RUTOR_CATEGORIES_QUERY = new Map([
  [RUTOR_CATEGORIES_QUERY_ANY, 0],
  [RUTOR_CATEGORIES_QUERY_MOVIES, 1],
  [RUTOR_CATEGORIES_QUERY_SERIES, 4],
  [RUTOR_CATEGORIES_QUERY_TVSHOWS, 6],
  [RUTOR_CATEGORIES_QUERY_CARTOONS, 7],
  [RUTOR_CATEGORIES_QUERY_ANIME, 10],
]);